print("Complete Name: Roger E. Bao Jr.")
print("Course: BSCS")
print("Section: CS1E")
print("Age: Classified")
print("Birthday: mm/dd/yyyy ")
print("Complete Home Address: Barra opol Mis. Or. Blk 24 Lot 13")